name: scrappingEnvironment
dependencies:
- python=3.7
- pip
- pip:
  - pandas==1.0.3
  - selenium==3.141.0
  - beautifulsoup4==4.8.2
  - tqdm==4.45.0
  - sqlalchemy==1.3.16
  - psycopg2-binary==2.8.5
  - yamldirs==1.1.8