version: '3.5'

services:
  selenium_chrome:
    container_name: prod_selenium_chrome
    build:
      context: ../..
      dockerfile: docker/selenium_chrome/Dockerfile
    ports:
    - 4444:4444
    shm_size: '8gb'

  postgre_db:
    container_name: prod_postgre_db
    build:
      context: ../..
      dockerfile: docker/postgres/Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: DDInvestorMetadata
    ports:
    - 5432:5432
    volumes:
    - type: volume
      source: prod_postgres
      target: /var/lib/postgresql/data
    command: postgres

volumes:
  prod_postgres:
    external: true