version: "3.5"

services:
  jupyterlab:
    container_name: jupyterlab
    build:
      context: .
      dockerfile: Dockerfile
        
    volumes:
      - type: bind
        source: ./
        target: /home/jovyan/lab
        
    ports:
      - 8888:8888
            
    tty: true